# Generated by Django 3.2.25 on 2026-03-09 05:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_time',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='idempotencyrecords',
            name='idempotency_key',
            field=models.CharField(default=uuid.uuid4, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает оплыты'), ('PAID', 'Оплачен'), ('CANCELED', 'Отменен')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='idempotency_key',
            field=models.CharField(default=uuid.uuid4, max_length=200, unique=True),
        ),
    ]
