# Generated by Django 3.2.25 on 2026-02-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20260224_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.CharField(default='-', max_length=1000),
        ),
    ]
