# Generated by Django 3.2.25 on 2026-03-10 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20260309_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproducts',
            old_name='product_price_freezed',
            new_name='order_price_freezed',
        ),
    ]
