# Generated by Django 3.2.25 on 2026-03-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_product_price_freezed_orderproducts_order_price_freezed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproducts',
            old_name='order_price_freezed',
            new_name='product_price_freezed',
        ),
    ]
