# Generated by Django 3.2.25 on 2026-03-12 14:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20260312_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencyrecords',
            name='idempotency_key',
            field=models.CharField(default=uuid.uuid4, max_length=200, unique=True, verbose_name='Ключ идемпотентности'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(default=uuid.uuid4, max_length=200, unique=True, verbose_name='Ключ идемпотентности'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.IntegerField(verbose_name='Сумма платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает оплаты'), ('PAID', 'Оплачен'), ('CANCELED', 'Отменен')], default='PENDING', max_length=10, verbose_name='Статус платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wallet', verbose_name='Кошелек пользователя'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='idempotency_key',
            field=models.CharField(default=uuid.uuid4, max_length=200, unique=True, verbose_name='Ключ идемпотентности'),
        ),
    ]
