# Generated by Django 3.2.25 on 2026-03-19 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20260319_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencyrecords',
            name='idempotency_key',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='idempotency_key',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
    ]
