# Generated by Django 3.2.25 on 2026-03-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20260319_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idempotencyrecords',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.AddField(
            model_name='idempotencyrecords',
            name='status_new',
            field=models.IntegerField(choices=[(1, 'Ожидает оплаты'), (2, 'Оплачен'), (3, 'Отменен')], default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='status_new',
            field=models.IntegerField(choices=[(1, 'Ожидает оплаты'), (2, 'Оплачен'), (3, 'Отменен')], default=1, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status_new',
            field=models.IntegerField(choices=[(1, 'Ожидает оплаты'), (2, 'Оплачен'), (3, 'Отменен')], default=1, verbose_name='Статус платежа'),
        ),
    ]
