# Generated by Django 3.2.25 on 2026-03-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20260319_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idempotencyrecords',
            old_name='status_new',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status_new',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='status_new',
            new_name='status',
        ),
    ]
