# Generated by Django 3.2.25 on 2026-03-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20260323_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencyrecords',
            name='idempotency_key',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='refund',
            name='idempotency_key',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
