# Generated by Django 3.2.25 on 2026-03-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20260323_1318'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('idempotency_key',), name='unique_idempotency_key_per_payment'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(fields=('idempotency_key',), name='unique_idempotency_key_per_order'),
        ),
    ]
