# Generated by Django 3.2.25 on 2026-03-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20260323_1324'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='idempotencyrecords',
            constraint=models.UniqueConstraint(fields=('namespace', 'idempotency_key'), name='unique_idempotency_key_per_namespace'),
        ),
    ]
