# Generated by Django 3.2.25 on 2026-04-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_orderproducts_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='core.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='product_price_freezed',
            field=models.IntegerField(verbose_name='Фиксированная цена заказа'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
