# Generated by Django 3.2.25 on 2026-04-01 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20260401_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.wallet', verbose_name='Кошелек пользователя'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.order'),
        ),
    ]
