# Generated by Django 3.2.25 on 2026-04-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20260401_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='product_price_freezed',
            field=models.PositiveIntegerField(verbose_name='Фиксированная цена заказа'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Сумма платежа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.PositiveIntegerField(verbose_name='Баланс кошелька'),
        ),
    ]
